### ISSUE TITLE
confusion

### ISSUE THREAD

**Issue by Notadumdum** [hanabizhani/SeleniumWebDriver-Tiny_projects#1]
hey bro im a bit confused on how to make use of this code here.....i normally use python but i have to use this java code cause theres no other option...please can you give your email address to clarify a stuff or two... i need a little bit of explanations bruh... or your instagram

**Comment by hanabizhani** [comment]
The issue is closed.
Note that you need just the base language of that project to run it. If the project is python based you only need to have python and the driver you want to run (geko, chrome,..)
